site_name: Lucia
site_url: https://mydomain.org/mysite
theme:
  logo: logolm.png
  name: material
  palette:
    primary: pink
  theme:
   font: 
    text: Roboto
  theme:
      features:
        - header.autohide

  features:
   - navigation.instant
   - navigation.instant.progress
   - navigation.instant.preview
   - navigation.tracking
   - navigation.tabs
   - navigation.tabs
   - navigation.tabs.sticky
   - navigation.sections
   - navigation.expand
   # -toc.integrate
   - navigation.top
   - navigation.footer


nav:
  - Home: index.md
  - About: 
    - Biografia: about/about.md
    - Documentazione: about/childhood.md

